# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da6e3f6bfacecb2ac09a1bf97d49372d3ac4d4d0b005c4ff5b4a5c622a55fda842a422296bd4fe0eaa5d7a645052e9f4912fc6e106a59c37c6a7c87668c0689d

staging:
  secret_key_base: 1ac5805693247715ca83030f490d484c0e6c9ec95a478369197c8d71cad324c832917255ed5f6a2b1c52baeed6191e049701acaf735a346ffd1232af6a6165e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
